### PR TITLE
Hey jordan i fixed js engine

### PR DESCRIPTION
**Pull request by Eric-R-Malice**
pull this please

### CODE REVIEW

**Comment by JordanSantiagoYT** [comment]
This doesn't fix anything. it just deletes the entire engine

**Comment by Cobalt-Bar** [comment]
WHEEZE

**Comment by Eric-R-Malice** [comment]
> This doesn't fix anything. it just deletes the entire engine
:trollface:

**Comment by MemeHovy** [comment]
> pull this please

hey buddy, did you drop out of first grade so you could make the most effortless thing ever? or did your parents just think you don't need an education because you can't ever grow up to make an effort?

**Comment by Eric-R-Malice** [comment]
> > pull this please
> 
> hey buddy, did you drop out of first grade so you could make the most effortless thing ever? or did your parents just think you don't need an education because you can't ever grow up to make an effort?

you must be fun at parties - ever heard of a joke?

**Comment by cyklusiguess** [comment]
auricular death 7

**Pull request closed without merging**
