### PR TITLE
Fix Most Deprecation Errors + Remove Flixel Overrides

### PR DESCRIPTION
**Pull request by CaptainBaldi**
Changes:
- Fixed most deprecation errors caused by updating libraries.
- Removed Flixel overrides (`FlxAnimationController`, `FlxRuntimeShader`)

flixel added a `animationTimeScale` variable into `FlxG` that functions the same way as `FlxAnimationController.globalSpeed`, so we don't need this override anymore.

flixel-addons added `FlxRuntimeShader` officially, so we don't need that file anymore either.

### CODE REVIEW

**Comment by moxie-coder** [comment]
gonna wait for CI before merging, will need some testing unless you did that already?

**Review by moxie-coder — APPROVED** [review]

**Comment by moxie-coder** [comment]
I may be sick, but I'm not gonna let that interfere, I took medicine so I should be fine for now 👍🏻

**Comment by JordanSantiagoYT** [comment]
cool

is this safe to merge yet? or is there still work needed to be done

**Comment by CaptainBaldi** [comment]
> cool
> 
> is this safe to merge yet? or is there still work needed to be done

This one should be good to go, ya

**Comment by JordanSantiagoYT** [comment]
Ok

**Pull request merged**
