### PR TITLE
Little fix for the scroll speed crash

### PR DESCRIPTION
**Pull request by MemeHovy**
I can't test if this works rn since I'm a little occupied rn

### CODE REVIEW

**Comment by MemeHovy** [comment]
> > a image
> 
> Tween issue It's seems like you are missing something LMAO

lol, of course

**Comment by JordanSantiagoYT** [comment]
IMG_9212
hmmmm

**Comment by MemeHovy** [comment]
it very much might be a tween issue

**Comment by JordanSantiagoYT** [comment]
i think it may be a tween issue!!

**Comment by JordanSantiagoYT** [comment]
tested, but now Change Scroll Speed only works if value 2 is either null or 0

image

https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/assets/61796448/a8102b72-106f-4bdf-a093-c30e5b3c2a9a

**Comment by JordanSantiagoYT** [comment]
> IMG_9212 hmmmm

the issue probably has something to do with this

**Comment by MemeHovy** [comment]
> > IMG_9212 hmmmm
> 
> the issue probably has something to do with this, specifically the "if (isSustainNote)" thing

because it's for resizing the sustains

**Comment by MemeHovy** [comment]
damn

**Comment by JordanSantiagoYT** [comment]
the hold notes acting weird is probably because i added a “!Math.isNaN(sustainLength)” check to the entire thing (which probably isn’t needed)

**Comment by Stefan2008Git** [comment]
> tested!! it works, only issue left to fix now is the hold notes
> 
>  2023-08-24.15-46-47.mp4 
> reupload, didnt embed apparently

OS Engine moment

**Comment by JordanSantiagoYT** [comment]
i think i found a fix

**Comment by JordanSantiagoYT** [comment]
public function resizeByRatio(ratio:Float) //haha funny twitter shit
	{
		if(isSustainNote && animation != null && animation.curAnim != null && !animation.curAnim.name.endsWith('end'))
		{
			scale.y *= ratio;
			updateHitbox();
		}
	}

this may be the fix

**Comment by MemeHovy** [comment]
mk

**Pull request merged**
