### PR TITLE
Videos path fix experiment 

### LINKED ISSUE #201: game buggy
### Describe your bug here. Mind you, if you are modding, please try testing your bug in a clean version of the engine instead, this ensures the bug is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version.

im trying to play the game but im getting a error
problem

### Command Prompt/Terminal logs (if existing)

_No response_

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

_No response_

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here.

Yes

### PR DESCRIPTION
**Pull request by moxie-coder**
closes #201

### CODE REVIEW

**Comment by JordanSantiagoYT** [comment]
is this a draft pr or is it ready to merge

**Comment by Stefan2008Git** [comment]
> is this a draft pr or is it ready to merge

Darft

**Comment by JordanSantiagoYT** [comment]
A, ok

**Comment by darklegion2605** [comment]
I love how the crash handerler works, making the "Can turn your bad pc into a better pc if you are having trouble lagging hard in the base one." mostly true; however, did you actully forget to add the offical fnf songs to the base of your no lag engine?

**Comment by moxie-coder** [comment]
> I love how the crash handerler works, making the "Can turn your bad pc into a better pc if you are having trouble lagging hard in the base one." mostly true; however, did you actully forget to add the offical fnf songs to the base of your no lag engine?

IMG_4359

**Pull request closed without merging**
