### PR TITLE
may this can fix the error

### PR DESCRIPTION
**Pull request by Hiho2950**

### CODE REVIEW

**Comment by JordanSantiagoYT** [comment]
image
e

**Comment by JordanSantiagoYT** [comment]
i guess android compiling doesn't fully work yet

**Comment by Hiho2950** [comment]
> i guess android compiling doesn't fully work yet

yep there is some errors in the android build

**Comment by Hiho2950** [comment]
> i guess android compiling doesn't fully work yet

i think it cant be fixed

**Comment by Hiho2950** [comment]
> i guess android compiling doesn't fully work yet

it works but auto close after flixel logo

**Comment by Hiho2950** [comment]
> > i guess android compiling doesn't fully work yet
> 
> it works but auto close after flixel logo

it makes a crash folder so there is a crash but no log so there is a problem on crash handler i think

**Comment by JordanSantiagoYT** [comment]
image
well it seems the game no longer crashes after opening, but now musicbeatstate crashes on line 53

**Comment by Hiho2950** [comment]
> image well it seems the game no longer crashes after opening, but now musicbeatstate crashes on line 53

idk i had do a temporaly fix is start at MainMenuState not TitleState and the line 53 is about setVirualPadUI i dont know why it crashes here

**Comment by JordanSantiagoYT** [comment]
image
i managed to get a more detailed crash

**Comment by Hiho2950** [comment]
> image i managed to get a more detailed crash

idk why it crashes in in a "}" line too in MainMenuState

**Comment by Hiho2950** [comment]
what ideas do you have to fix errors?

**Comment by JordanSantiagoYT** [comment]
i think this may fix it?
		#if android
		MusicBeatState.addVirtualPad(UP_DOWN, A_B_C);
		virtualPad.y = -48;
		#end

**Comment by Hiho2950** [comment]
> i think this may fix it? #if android MusicBeatState.addVirtualPad(UP_DOWN, A_B_C); virtualPad.y = -48; #end

it s already added and i have an idea to remove it temporaly to know what is the exact error

**Comment by Hiho2950** [comment]
and why the fast compile dont works on androidbuild!?

**Comment by JordanSantiagoYT** [comment]
> it s already added and i have an idea to remove it temporaly to know what is the exact error

yeah, but the current code only does "addVirtualPad(UP_DOWN, A_B_C);"
the null object reference might be because addVirtualPad doesn't exist in MainMenuState, but it does in MusicBeatState

**Comment by JordanSantiagoYT** [comment]
image
this line causes MusicBeatState to crash upon running addVirtualPad apparently

**Comment by Hiho2950** [comment]
> image this line causes MusicBeatState to crash upon running addVirtualPad apparently

but it wont crash on other ports!?

**Comment by JordanSantiagoYT** [comment]
i have no idea why this is the only port that function crashes on

**Comment by Hiho2950** [comment]
> i have no idea why this is the only port that function crashes on

idk. when the port works i will add an hx file support on your engine,ok?

**Comment by Hiho2950** [comment]
@JordanSantiagoYT can ask about your nationality because i think you're from jordan

**Comment by JordanSantiagoYT** [comment]
ah ive seen several people think i'm from the country "Jordan" because my first name is jordan

i'm from the united states LOL

**Comment by Hiho2950** [comment]
> ah ive seen several people think i'm from the country "Jordan" because my first name is jordan
> 
> i'm from the united states LOL

LOL i was thinking you're arabian like me

**Comment by Hiho2950** [comment]
> i have no idea why this is the only port that function crashes on

i will try to fix somethings

**Comment by Hiho2950** [comment]
i had found an error on SUtil with #if android

**Comment by JordanSantiagoYT** [comment]
> and why the fast compile dont works on androidbuild!?

because apparently the actions didn't have permission to clear/save the cache because write access wasnt toggled? ive toggled it back on so it should work

**Comment by Hiho2950** [comment]
> > and why the fast compile dont works on androidbuild!?
> 
> because apparently the actions didn't have permission to clear/save the cache because write access wasnt toggled? ive toggled it back on so it should work

but it gives that there is an save and restore but i dont see anything from them

**Pull request merged**
