### PR TITLE
Adding Android support since Jordan wanted that

### PR DESCRIPTION
**Pull request by Stefan2008Git**
_ It's W.I.P because i need to add more functions!

### CODE REVIEW

**Comment by Stefan2008Git** [comment]
> gameplay changers substate line 372 fix if(controls.RESET && FlxG.keys.pressed.SHIFT #if android || virtualPad.buttonC.justPressed #end)

Uhhhhhh
I don't know XD. Tried my best

**Comment by JordanSantiagoYT** [comment]
i'll merge it for right now and fix it from there

**Comment by JordanSantiagoYT** [comment]
a whoopsie
image

**Comment by JordanSantiagoYT** [comment]
some stuff is missing so that would be a cause for most of the errors here

**Comment by Stefan2008Git** [comment]
> some android stuff is missing so that would be a cause for most of the errors here

Opps, my bad

**Comment by Stefan2008Git** [comment]
I told you it's W.I.P because it's missing some stuff and functions dude, so that's why

**Comment by Stefan2008Git** [comment]
> some android stuff is missing so that would be a cause for most of the errors here

Well, you should use MaysLastPlays fork of extension-androidtools for SUtil because it's required

**Comment by JordanSantiagoYT** [comment]
image
well i mean it does install that fork of extension-androidtools

**Comment by Stefan2008Git** [comment]
> image well i mean it does install that fork of extension-androidtools

Did you installed tho?

**Comment by JordanSantiagoYT** [comment]
image
pretty sure yeah

**Comment by Stefan2008Git** [comment]
> image pretty sure yeah

Uhhh, can you check it simply typing: "``haxelib list``"?

**Comment by JordanSantiagoYT** [comment]
image

**Comment by JordanSantiagoYT** [comment]
oh yeah were doing this in the github workflow

**Comment by Stefan2008Git** [comment]
> a whoopsie image

You should delete this stuff and add it:
1. For OptionsState add ``var customizeAndroidControlsTipText:FlxText;``
2. For FlxHitbox detele a ``backend.ClientPrefs``, ``ClientPrefs.hitboxAlpha`` and for FlxButton delete ``backend.ClientPrefs``, ``ClientPrefs.virtualPadAlpha`` because i forgot to delete that
3. Delete on AndroidControlsSubState ``var velocityBackground:FlxBackdrop`` because again i forgot to remove it

**Comment by JordanSantiagoYT** [comment]
image
it appears to have fixed most of the issues

**Comment by Stefan2008Git** [comment]
> image it appears to have fixed most of the issues

Ahhh, you can remove that too. I forgot to say. What the heck wrong with me? Oh my goodness, my brain is so confused this days tho

**Pull request merged**
