### PR TITLE
Updated Libraries WIP

### PR DESCRIPTION
**Pull request by CaptainBaldi**
Current changes:
- Compilation now works with latest libraries (ONLY TESTED ON WINDOWS)
- Changed the Discord RPC library from `discord_rpc` to `hxdiscord_rpc`
- Removed a LOT of overrides

To Do:
- Fix Performance Display (FPS, Memory)
- Testing

I only have a Windows machine, so I am unable to test on other platforms. I am unsure if JS Engine prioritizes support for platforms other than Windows, but even if not, I would like to have this tested a bit more to make sure this does not break any core features.

**DO NOT MERGE THIS YET**

### CODE REVIEW

**Comment by CaptainBaldi** [comment]
@JordanSantiagoYT if you don't mind, can i contact you on discord so it's easier to discuss, i don't think i have your username

**Comment by StinkTheStinker** [comment]
holy fucking shit bruh
image
thats alot of deleted stuff

**Comment by CaptainBaldi** [comment]
image
:c_:

**Comment by CobaltBar** [comment]
wait this is a legit pr

only pr i've seen other than this was deleting the entire engine

**Comment by JordanSantiagoYT** [comment]
WAIT i forgot one issue with this, if i merge this itll remove long song support

**Comment by JordanSantiagoYT** [comment]
> @JordanSantiagoYT if you don't mind, can i contact you on discord so it's easier to discuss, i don't think i have your username

i don't have discord, i haven't had it since october

**Comment by CaptainBaldi** [comment]
> WAIT i forgot one issue with this, if i merge this itll remove long song support

image

actually, in the latest versions of openfl/lime, a change was made to support longer audio

i'm not exactly sure what the new limit is, but i tested with splitathon 2 and that managed to work

**Comment by CaptainBaldi** [comment]
> > @JordanSantiagoYT if you don't mind, can i contact you on discord so it's easier to discuss, i don't think i have your username
> 
> i don't have discord, i haven't had it since october

aw ok, shame

**Comment by JordanSantiagoYT** [comment]
> > WAIT i forgot one issue with this, if i merge this itll remove long song support
> 
> image
> 
> actually, in the latest versions of openfl/lime, a change was made to support longer audio
> 
> i'm not exactly sure what the new limit is, but i tested with splitathon 2 and that managed to work

oh

**Comment by JordanSantiagoYT** [comment]
> wait this is a legit pr
> 
> only pr i've seen other than this was deleting the entire engine

yeah it was someone in the psych engine discord, most of the people there talk bad about js engine, to the point where a js engine ban was even considered in the server

**Comment by CaptainBaldi** [comment]
with this commit, i removed `MusicBeatState.switchState`, and `MusicBeatState.resetState`. these functions only existed for transitions, and with the new haxeflixel state switch stuff, were causing crashes. but with the help of the haxeflixel discord, we found a way to do it without these functions.
`FlxG.switchState` and `FlxG.resetState` are now to be used instead

**Comment by CaptainBaldi** [comment]
on another note, all i have to do with this pr (that i can recall) is recreate the performance counter, and fix a bug where songs without voices will crash (due to a change within openfl)

**Comment by JordanSantiagoYT** [comment]
> fix a bug where songs without voices will crash (due to a change within openfl)

wait songs without voices dont work anymore? i thought the flxsound thing would fix it

**Comment by Stefan2008Git** [comment]
> > fix a bug where songs without voices will crash (due to a change within openfl)
> 
> wait songs without voices dont work anymore? i thought the flxsound thing would fix it

No dude, it doesn't. You should use the latest stuff because the old one will just break everything and make engine unplayable with oldest stuff. That happens to me when i enter to state, it should show Null Object Reference without any reason. Doesn't matter if you delete ot bring back the code, it will crash because of older Flixel stuff, so i ak recommending to use latest Flixel stuff

**Comment by Stefan2008Git** [comment]
> holy fucking shit bruh image thats alot of deleted stuff

Remember? It's time to use the latest Flixel stuff to fix this shit

**Comment by JordanSantiagoYT** [comment]
> > > WAIT i forgot one issue with this, if i merge this itll remove long song support
> > 
> > 
> > image
> > actually, in the latest versions of openfl/lime, a change was made to support longer audio
> > i'm not exactly sure what the new limit is, but i tested with splitathon 2 and that managed to work
> 
> oh


image

little update, i removed the openfl/media and lime folders and updated to the latest openfl and lime.. splitathon 2 doesn't work for me. am i doing smth wrong?

**Comment by JordanSantiagoYT** [comment]
> > > fix a bug where songs without voices will crash (due to a change within openfl)
> > 
> > 
> > wait songs without voices dont work anymore? i thought the flxsound thing would fix it
> 
> No dude, it doesn't. You should use the latest stuff because the old one will just break everything and make engine unplayable with oldest stuff. That happens to me when i enter to state, it show Null Object Reference without any reason. Doesn't matter if you delete ot bring back the code, it will crash because of older Flixel stuff, so i am recommending to use latest Flixel stuff

But when you use the new hxcpp, making graphics always gives a transparent color. that's why i use 4.2.1 instead

**Comment by Stefan2008Git** [comment]
> > > > fix a bug where songs without voices will crash (due to a change within openfl)
> > > 
> > > 
> > > wait songs without voices dont work anymore? i thought the flxsound thing would fix it
> > 
> > 
> > No dude, it doesn't. You should use the latest stuff because the old one will just break everything and make engine unplayable with oldest stuff. That happens to me when i enter to state, it show Null Object Reference without any reason. Doesn't matter if you delete ot bring back the code, it will crash because of older Flixel stuff, so i am recommending to use latest Flixel stuff
> 
> But when you use the new hxcpp, making graphics always gives a transparent color. that's why i use 4.2.1 instead

Me when you use the latest Haxe to fix that issue:

Actually it's time to use the latest Haxe version tho

**Comment by JordanSantiagoYT** [comment]
> > > > > fix a bug where songs without voices will crash (due to a change within openfl)
> > > > 
> > > > 
> > > > wait songs without voices dont work anymore? i thought the flxsound thing would fix it
> > > 
> > > 
> > > No dude, it doesn't. You should use the latest stuff because the old one will just break everything and make engine unplayable with oldest stuff. That happens to me when i enter to state, it show Null Object Reference without any reason. Doesn't matter if you delete ot bring back the code, it will crash because of older Flixel stuff, so i am recommending to use latest Flixel stuff
> > 
> > 
> > But when you use the new hxcpp, making graphics always gives a transparent color. that's why i use 4.2.1 instead
> 
> Me when you use the latest Haxe to fix that issue:
> 
> Actually it's time to use the latest Haxe version tho

that's funny, because the website i need to use to get the newest haxe version is blocked

**Comment by Stefan2008Git** [comment]
> > > > > > fix a bug where songs without voices will crash (due to a change within openfl)
> > > > > 
> > > > > 
> > > > > wait songs without voices dont work anymore? i thought the flxsound thing would fix it
> > > > 
> > > > 
> > > > No dude, it doesn't. You should use the latest stuff because the old one will just break everything and make engine unplayable with oldest stuff. That happens to me when i enter to state, it show Null Object Reference without any reason. Doesn't matter if you delete ot bring back the code, it will crash because of older Flixel stuff, so i am recommending to use latest Flixel stuff
> > > 
> > > 
> > > But when you use the new hxcpp, making graphics always gives a transparent color. that's why i use 4.2.1 instead
> > 
> > 
> > Me when you use the latest Haxe to fix that issue:
> > Actually it's time to use the latest Haxe version tho
> 
> that's funny, because the website i need to use to get the newest haxe version is blocked

https://haxe.org/download/

**Comment by JordanSantiagoYT** [comment]
> > > > > > > fix a bug where songs without voices will crash (due to a change within openfl)
> > > > > > 
> > > > > > 
> > > > > > wait songs without voices dont work anymore? i thought the flxsound thing would fix it
> > > > > 
> > > > > 
> > > > > No dude, it doesn't. You should use the latest stuff because the old one will just break everything and make engine unplayable with oldest stuff. That happens to me when i enter to state, it show Null Object Reference without any reason. Doesn't matter if you delete ot bring back the code, it will crash because of older Flixel stuff, so i am recommending to use latest Flixel stuff
> > > > 
> > > > 
> > > > But when you use the new hxcpp, making graphics always gives a transparent color. that's why i use 4.2.1 instead
> > > 
> > > 
> > > Me when you use the latest Haxe to fix that issue:
> > > Actually it's time to use the latest Haxe version tho
> > 
> > 
> > that's funny, because the website i need to use to get the newest haxe version is blocked
> 
> https://haxe.org/download/

that's the website im talking about lol

**Comment by JordanSantiagoYT** [comment]
Nvm got it

**Comment by Stefan2008Git** [comment]
> > > > > > > > fix a bug where songs without voices will crash (due to a change within openfl)
> > > > > > > 
> > > > > > > 
> > > > > > > wait songs without voices dont work anymore? i thought the flxsound thing would fix it
> > > > > > 
> > > > > > 
> > > > > > No dude, it doesn't. You should use the latest stuff because the old one will just break everything and make engine unplayable with oldest stuff. That happens to me when i enter to state, it show Null Object Reference without any reason. Doesn't matter if you delete ot bring back the code, it will crash because of older Flixel stuff, so i am recommending to use latest Flixel stuff
> > > > > 
> > > > > 
> > > > > But when you use the new hxcpp, making graphics always gives a transparent color. that's why i use 4.2.1 instead
> > > > 
> > > > 
> > > > Me when you use the latest Haxe to fix that issue:
> > > > Actually it's time to use the latest Haxe version tho
> > > 
> > > 
> > > that's funny, because the website i need to use to get the newest haxe version is blocked
> > 
> > 
> > https://haxe.org/download/
> 
> that's the website im talking about lol

image
?

**Comment by JordanSantiagoYT** [comment]
> > > > > > > > > fix a bug where songs without voices will crash (due to a change within openfl)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > wait songs without voices dont work anymore? i thought the flxsound thing would fix it
> > > > > > > 
> > > > > > > 
> > > > > > > No dude, it doesn't. You should use the latest stuff because the old one will just break everything and make engine unplayable with oldest stuff. That happens to me when i enter to state, it show Null Object Reference without any reason. Doesn't matter if you delete ot bring back the code, it will crash because of older Flixel stuff, so i am recommending to use latest Flixel stuff
> > > > > > 
> > > > > > 
> > > > > > But when you use the new hxcpp, making graphics always gives a transparent color. that's why i use 4.2.1 instead
> > > > > 
> > > > > 
> > > > > Me when you use the latest Haxe to fix that issue:
> > > > > Actually it's time to use the latest Haxe version tho
> > > > 
> > > > 
> > > > that's funny, because the website i need to use to get the newest haxe version is blocked
> > > 
> > > 
> > > https://haxe.org/download/
> > 
> > 
> > that's the website im talking about lol
> 
> image ?

Erm.

Website blocking only applies to my computer, not yours

**Comment by CaptainBaldi** [comment]
> > fix a bug where songs without voices will crash (due to a change within openfl)
> 
> wait songs without voices dont work anymore? i thought the flxsound thing would fix it

it seems to only be an issue if you have Progressive Audio Loading disabled, I managed to fix it though
In latest openfl versions if a sound can't be found when using `fromFile` for some reason it throws an error

**Comment by JordanSantiagoYT** [comment]
Okay, this time i updated to the newest haxe

**Comment by CaptainBaldi** [comment]
> > > > WAIT i forgot one issue with this, if i merge this itll remove long song support
> > > 
> > > 
> > > image
> > > actually, in the latest versions of openfl/lime, a change was made to support longer audio
> > > i'm not exactly sure what the new limit is, but i tested with splitathon 2 and that managed to work
> > 
> > 
> > oh
> 
> image
> 
> little update, i removed the openfl/media and lime folders and updated to the latest openfl and lime.. splitathon 2 doesn't work for me. am i doing smth wrong? image i'm positive im using the right version
> 
> image
> 
> Update 2! i removed and reinstalled both libraries. it still doesn't work.

image
Well, I can say it's definitely working on my end, you may also need latest Flixel? but i don't think that would affect much

**Comment by Stefan2008Git** [comment]
> Okay, this time i updated to the newest haxe. im seeing if Stefan's right about updating to the newest haxe fixing the HxCPP issue

I told you, but no. Everything what are you thinking it's gonna just fuck everything, but i am telling the truth the latest Haxe version can fix everything and yeah, use this file if you can't use the official Haxe version
[haxe-4.3.3-win64.zip](https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/files/14157018/haxe-4.3.3-win64.zip)

**Comment by JordanSantiagoYT** [comment]
> > > > > WAIT i forgot one issue with this, if i merge this itll remove long song support
> > > > 
> > > > 
> > > > image
> > > > actually, in the latest versions of openfl/lime, a change was made to support longer audio
> > > > i'm not exactly sure what the new limit is, but i tested with splitathon 2 and that managed to work
> > > 
> > > 
> > > oh
> > 
> > 
> > image
> > little update, i removed the openfl/media and lime folders and updated to the latest openfl and lime.. splitathon 2 doesn't work for me. am i doing smth wrong? image i'm positive im using the right version
> > image
> > Update 2! i removed and reinstalled both libraries. it still doesn't work.
> 
> image Well, I can say it's definitely working on my end, you may also need latest Flixel? but i don't think that would affect much

Yeah, i updated to newest flixel and..
image

**Comment by JordanSantiagoYT** [comment]
mini update: removed the flxsound override and it compiles now!

**Comment by JordanSantiagoYT** [comment]
image

stefan you said updating to the latest haxe version would fix this

**Comment by JordanSantiagoYT** [comment]
image
that aside, splitathon 2 works now

**Comment by Stefan2008Git** [comment]
> image
> 
> stefan you said updating to the latest haxe version would fix this

That's normal for me, but i don't know why is not working for you. Did you installed latest Have version?


Haxe version
image

Haxelib libraries
image

Credits menu with latest Hxcpp version
image

Sustains long tail notes
image

**Comment by JordanSantiagoYT** [comment]
> > image
> > stefan you said updating to the latest haxe version would fix this
> 
> That's normal for me, but i don't know why is not working for you. Did you installed latest Have version?
> 
> Haxe version image
> 
> Haxelib libraries image
> 
> Credits menu with latest Hxcpp version image
> 
> Sustains long tail notes image

That's literally not a haxe issue. It's an issue with hxcpp 4.3.2. That's why I use 4.2.1 instead

**Comment by Stefan2008Git** [comment]
> > > image
> > > stefan you said updating to the latest haxe version would fix this
> > 
> > 
> > That's normal for me, but i don't know why is not working for you. Did you installed latest Have version?
> > Haxe version image
> > Haxelib libraries image
> > Credits menu with latest Hxcpp version image
> > Sustains long tail notes image
> 
> That's literally not a haxe issue. It's an issue with hxcpp 4.3.2. That's why I use 4.2.1 instead

Well, well, well. So you want to use old broken Flixel stuff to make your engine laggy? Dude, you need to accept that is your problem. You just didn't even installed the latest Haxe version. Is required an latest Haxe version to show correct FlxColor

**Comment by CaptainBaldi** [comment]
> image that aside, splitathon 2 works now
> 
> it seems the new limit is 3 hours, as I tried loading the Desert Bus song with a higher sample rate and it crashes, but at 8000 it doesnt

Just curious, what is JS's limit currently?

**Comment by JordanSantiagoYT** [comment]
> Just curious, what is JS's limit currently?

Same limit as before

**Comment by JordanSantiagoYT** [comment]
Deleted stefan's comment because he keeps acting smart like using haxe 4.3.2/4.3.3 actually fixes it

**Comment by JordanSantiagoYT** [comment]
image

image

Using Haxe 4.3.3 and it's still not working. So stop acting like you're smart

**Comment by Stefan2008Git** [comment]
> Deleted stefan's comment because he keeps acting smart like using haxe 4.3.2/4.3.3 actually fixes it

...

**Comment by Stefan2008Git** [comment]
> image
> 
> image
> 
> Using Haxe 4.3.3 and it's still not working. So stop acting like you're smart

...

**Comment by JordanSantiagoYT** [comment]
ok MAYBE i was a bit rude but. i still got my point across. the making graphics bug is still present in the newest hxcpp version even with the latest haxe installed.

**Comment by Stefan2008Git** [comment]
> ok MAYBE i was a bit rude but. i still got my point across. the making graphics bug is still present in the newest hxcpp version even with the latest haxe installed.

...

**Comment by Stefan2008Git** [comment]
> > ok MAYBE i was a bit rude but. i still got my point across. the making graphics bug is still present in the newest hxcpp version even with the latest haxe installed.
> 
> ...

You don't know how i am getting abused every single fucking day, so that's why i am typing "..." now

**Comment by CaptainBaldi** [comment]
I'm unsure on why pushing the newest changes closed this? I'll reopen when I get certain things fixed

**Comment by Stefan2008Git** [comment]
> > @JordanSantiagoYT if you don't mind, can i contact you on discord so it's easier to discuss, i don't think i have your username
> 
> i don't have discord, i haven't had it since october

Could you tell a exactly reason why you can't use the Discord anymore? You are under 13 or what or you don't have the permission to use it?

**Pull request closed without merging**
