### PR TITLE
Almost done maybe....

### PR DESCRIPTION
**Pull request by Stefan2008Git**
I will see if something is missing, then i will fix that
- Don't even delete for Android assets because is reuqred for virtual pads and hitbox too @JordanSantiagoYT

### CODE REVIEW

**Comment by Stefan2008Git** [comment]
GUHHHHHHH!!!!!!!!!!!!!!!!!
Expected expression, _**B_R_U_H**_

**Comment by Hiho2950** [comment]
there is sdl error when i had try that's why i had do a pull request

**Comment by Stefan2008Git** [comment]
> there is sdl error when i had try that's why i had do a pull request

Uhhhhhhhhhh, i don't know then

**Comment by Hiho2950** [comment]
> > there is sdl error when i had try that's why i had do a pull request
> 
> Uhhhhhhhhhh, i don't know then

i had test the port on my phone

**Comment by Stefan2008Git** [comment]
> there is sdl error when i had try that's why i had do a pull request

Then send the pull request tho

**Comment by Hiho2950** [comment]
> > there is sdl error when i had try that's why i had do a pull request
> 
> Then send the pull request tho

i had do in jordan's repository

**Comment by Hiho2950** [comment]
i had fix the expression error and do a pull request

**Pull request merged**
